version: '3.4'
services:
    ace-db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'ace'
        expose:
            - '3306'
        volumes:
            - ace-db-volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        hostname: ace-db
        
    ace:
        build:
            context: .
            dockerfile: Dockerfile.ace-dev
        image: ace-dev:latest
        depends_on:
            - ace-db
        command: /bin/sh -c "while sleep 1000; do :; done"
        restart: always
        volumes:
            - .:/opt/ace
            - ace-data-volume:/opt/ace/data
            #- ./aceapi:/opt/ace/aceapi
            #- ./app:/opt/ace/app
            #- ./bin:/opt/ace/bin
            #- ./bro:/opt/ace/bro
            #- ./cron:/opt/ace/cron
            #- ./docker:/opt/ace/docker
            #- ./documentation:/opt/ace/documentation
            #- ./etc:/opt/ace/etc
            #- ./hunts:/opt/ace/hunts
            #- ./installer:/opt/ace/installer
            #- ./saq:/opt/ace/saq
            #- ./sql:/opt/ace/sql
            #- ./ssl:/opt/ace/ssl
            #- ./test_data:/opt/ace/test_data
            #- ./tests:/opt/ace/tests
        hostname: ace
volumes:
    ace-data-volume:
        name: ace-data-dev

    ace-db-volume:
        name: ace-db-dev
        
