version: '3.4'
services:
    ace-db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        expose:
            - '3306'
        volumes:
            - ace-db-volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        hostname: ace-db
        container_name: ace-db-dev
        
    ace:
        build:
            context: .
            dockerfile: Dockerfile.ace-dev-nonbind
        image: ace-dev-nonbind:latest
        depends_on:
            - ace-db
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - ace-opt-volume:/opt
            - ace-home-volume:/home/ace
        hostname: ace
        container_name: ace-dev
volumes:
    ace-opt-volume:
        name: ace-opt-dev

    ace-home-volume:
        name: ace-home-dev

    ace-db-volume:
        name: ace-db-dev
        
