version: '3.4'
services:
    ace-db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ace-db-volume:/var/lib/mysql
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d

    ace-http:
        image: ace-http:latest
        restart: always
        ports:
            - '8080:80'
        expose:
            - '80'
    ace:
        image: ace-alpine:latest
        depends_on:
            - ace-db
        command: docker/provision/ace/setup
        restart: always
        volumes:
            - ace-data-volume:/opt/ace/data
volumes:
    ace-db-volume:
        name: ace-db

    ace-data-volume:
        name: ace-data
